### numpy practise

In [26]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr, "\n")
arr0 = np.array([[1.5, 2, 3], [4, 5, 6]])
print(arr0, "\n")
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype = float)
print(arr1, "\n")

shape = arr1.shape
print(shape)
dim = arr1.ndim
print(dim)

arr1[0][0:3]

arr1.mean()

[1 2 3 4] 

[[1.5 2.  3. ]
 [4.  5.  6. ]] 

[[1. 2. 3.]
 [4. 5. 6.]] 

(2, 3)
2


np.float64(3.5)